[program:kaayos-ml]
process_name=%(program_name)s
command=/var/www/KaAyos/ml_service/venv/bin/uvicorn main:app --host 127.0.0.1 --port 8001
directory=/var/www/KaAyos/ml_service
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/var/log/kaayos-ml.log
stopwaitsecs=30
