[program:kaayos-reverb]
process_name=%(program_name)s
command=php /var/www/KaAyos/kaayos/artisan reverb:start
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/log/kaayos-reverb.log
stopwaitsecs=3600
